# Generated by Django 5.1 on 2026-04-28 05:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درس')),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('lesson_type', models.CharField(choices=[('VIDEO', 'ویدیو'), ('TEXT', 'متن'), ('QUIZ', 'آزمون'), ('ASSIGNMENT', 'تکلیف'), ('LIVE', 'جلسه زنده')], default='VIDEO', max_length=20, verbose_name='نوع درس')),
                ('content', models.TextField(blank=True, verbose_name='محتوای متنی')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو')),
                ('video_duration', models.PositiveIntegerField(default=0, help_text='مدت زمان ویدیو به ثانیه', verbose_name='مدت ویدیو (ثانیه)')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='لیست فایل\u200cهای ضمیمه', verbose_name='فایل\u200cهای ضمیمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_preview', models.BooleanField(default=False, help_text='آیا این درس برای پیش\u200cنمایش رایگان است؟', verbose_name='پیش\u200cنمایش رایگان')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون (مثل: fa-code)', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('detailed_description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/%Y/%m/', verbose_name='تصویر شاخص')),
                ('preview_video', models.URLField(blank=True, verbose_name='ویدیو معرفی')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف')),
                ('is_free', models.BooleanField(default=False, verbose_name='دوره رایگان')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'مبتدی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته'), ('EXPERT', 'حرفه\u200cای')], default='BEGINNER', max_length=20, verbose_name='سطح دشواری')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='مدت زمان کل دوره به ساعت', verbose_name='مدت زمان (ساعت)')),
                ('language', models.CharField(default='فارسی', max_length=50, verbose_name='زبان')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('ARCHIVED', 'بایگانی شده')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='دوره ویژه')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر دانشجو')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='پیش\u200cنیازهای دوره (لیست)', verbose_name='پیش\u200cنیازها')),
                ('learning_outcomes', models.JSONField(blank=True, default=list, help_text='نتایج یادگیری (لیست)', verbose_name='نتایج یادگیری')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='دسته\u200cبندی')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('COMPLETED', 'تکمیل شده'), ('EXPIRED', 'منقضی شده'), ('CANCELLED', 'لغو شده')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('expires_at', models.DateTimeField(blank=True, help_text='تاریخ انقضای دسترسی (برای دوره\u200cهای محدود)', null=True, verbose_name='تاریخ انقضا')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='آخرین دسترسی')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='روش پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه تراکنش')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='دوره')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('watch_time_seconds', models.PositiveIntegerField(default=0, help_text='زمان تماشای ویدیو به ثانیه', verbose_name='زمان تماشا (ثانیه)')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, help_text='آخرین موقعیت پخش ویدیو', verbose_name='موقعیت آخر (ثانیه)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.enrollment', verbose_name='ثبت\u200cنام')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'پیشرفت درس',
                'verbose_name_plural': 'پیشرفت درس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان نظر')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نظر ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='دوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان بخش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش\u200cها',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section', verbose_name='بخش'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', '-created_at'], name='courses_cou_status_41eebb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'status'], name='courses_cou_instruc_98570d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='courses_cou_categor_c23a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='courses_enr_student_c86bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='courses_enr_course__78d524_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='courses_les_enrollm_1a9f99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', 'is_approved'], name='courses_rev_course__ff83f2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='courses_rev_created_aeac4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'order')},
        ),
    ]
