# Generated by Django 5.1 on 2026-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_slug_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='course_previews/'),
        ),
    ]
